trigger:
  - main

pool:
  name: Default

stages:
  - stage: BuildAndTest
    displayName: "Build & Run Unit Tests"
    jobs:
      - job: Build
        steps:
          - checkout: self
          - script: |
              dotnet restore
              dotnet build --no-restore
              dotnet test --no-build --logger "trx;LogFileName=test_results.trx"
            displayName: "Build and Run Tests"


